package errorMsg;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.TreeSet;
import java.util.TreeMap;
import java.io.PrintStream;

/**
 * A class that hold all of the messages generated by the compiler.
 */
public class ErrorMsg
{
    private TreeMap<Integer,Integer> lines;
    private TreeSet<CompMessage> messages;
    private int lineNum;
    private String file;
    public boolean anyErrors;
    public boolean anyWarnings;

    /**
     * Create an ErrorMsg object.
     *
     * @param f the file we're compiling.
     */
    public ErrorMsg(String f)
    {
        file = f;
        lines = new TreeMap<Integer,Integer>();
        lines.put(-1,0);
        lines.put(0,1);
        lineNum = 1;
        messages = new TreeSet<CompMessage>();
        anyErrors = false;
    }

    /**
     * @return the name of the file we're compiling
     */
    public String getFileName() {return file;}

    /**
     * mark that pos is a newline.
     *
     * @param pos the character position of the new line.
     */
    public void newline(int pos)
    {
        lineNum++;
        lines.put(pos,lineNum);
    }

    /**
     * Returs a string representing the line and character position of pos.
     * DON'T USE THIS.  It's only there for WrangLR
     */
    public String lineAndChar(int pos)
    {
        int linePos = lines.floorKey(pos);
        return lines.get(linePos) + "." + (pos-linePos);
    }

    /**
     * register an error at the current position.
     *
     * @param pos the position of the error
     * @param err the error to register
     */
    public void error(int pos, CompError err)
    {
        int linePos = lines.floorKey(pos);
        int line = lines.get(linePos);
        err.line = line;
        err.chr = pos-linePos;
        err.file = file;
        messages.add(err);
        anyErrors = true;
    }

    /**
     * register a warning at the current position.
     *
     * @param pos the position of the warning
     * @param warn the warning to register
     */
    public void warning(int pos, CompWarning warn)
    {
        int linePos = lines.floorKey(pos);
        int line = lines.get(linePos);
        warn.line = line;
        warn.chr = pos-linePos;
        warn.file = file;
        messages.add(warn);
        anyWarnings = true;
    }

    /**
     * register a token at the current position.
     *
     * @param pos the position of the token
     * @param s the token to register
     */
    public void token(int pos, String s)
    {
        int linePos = lines.floorKey(pos);
        int line = lines.get(linePos);
        Token t = new Token(s);
        t.line = line;
        t.chr = pos-linePos;
        t.file = file;
        messages.add(t);
    }

    /**
     * register some thing at the current position.
     *
     * @param pos the position of the thing
     * @param s the thing to register
     */
    public void info(int pos, String s)
    {
        int linePos = lines.floorKey(pos);
        int line = lines.get(linePos);
        CompMessage m = new CompMessage(s);
        m.line = line;
        m.chr = pos-linePos;
        m.file = file;
        messages.add(m);
    }

    /**
     * Register an error by giving the error message.
     * DON'T USE THIS, it's only there for WrangLR.
     */
    public void error(int pos, String s)
    {
        int linePos = lines.floorKey(pos);
        int line = lines.get(linePos);
        CompMessage m = new CompError(s);
        m.line = line;
        m.chr = pos-linePos;
        m.file = file;
        messages.add(m);
        anyErrors = true;
    }

    /**
     * Print out all of the messages we've registered.
     */
    public void printMessages()
    {
        for(CompMessage msg : messages)
        {
            System.out.println(msg);
        }
    }
    public void printMessages(PrintStream out)
    {
        for(CompMessage msg : messages)
        {
            out.println(msg);
        }
    }

    public void writeMessages(StringBuilder sb)
    {
        for(CompMessage msg : messages)
        {
            sb.append(msg+"\n");
        }
    }

    public boolean equals(ErrorMsg other)
    {
        return messages.equals(other.messages);
    }
}
